<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<table id="tu"></table>
<div id="dg" style="text-align: center"><h2 id="ti" style="margin-top:40px"></h2></div>
<div id="dh" style="text-align: center"><h2 id="th" style="margin-top:40px"></h2></div>
<script type="text/javascript">
	var tools = [
		{
			iconCls:'icon-add',
			text:'冻结用户',
			width:100,
			handler:function(){
				var ss = $("#tu").datagrid("getSelected");
				if(ss==null){
					$("#dg").dialog("open");
					$("#ti").html("请选择要冻结的用户！");
				}else{
					if(ss.status==0){
						$("#dg").dialog("open");
						$("#ti").html("此用户已经被冻结！");
						setTimeout(function(){
							$("#dg").dialog("close");
						},2000);
					}else{
						$("#dh").dialog("open");
						$("#th").html("您确定要冻结此用户？");
					}
				}
			}
		},
		{
			iconCls:'icon-redo',
			text:'导出用户',
			width:100,
			handler:function(){
				$.ajax({
					type:"post",
					url:"${pageContext.request.contextPath}/user/exportUser",
					dataType:'json',
					success:function(a){
						if(a=="ok"){
							$("#dg").dialog("open");
							$("#ti").html("恭喜您，导出用户成功！");
							setTimeout(function(){
								$("#dg").dialog("close");
							},2000);
						}else{
							$("#dg").dialog("open");
							$("#ti").html("很遗憾，导出用户失败！");
							setTimeout(function(){
								$("#dg").dialog("close");
							},2000);
						}
					}
				});
			}
		}
	];
	var btns = [
		{
			iconCls:'icon-ok',
			text:'确定',
			width:80,
			height:30,
			handler:function(){
				$("#dh").dialog("close");
				$.ajax({
					type:"post",
					data:"id="+$("#tu").datagrid("getSelected").id,
					url:"${pageContext.request.contextPath}/user/modify",
					success:function(a){
						if(a=="ok"){
							$("#dg").dialog("open");
							$("#ti").html("恭喜您，冻结用户成功！");
						}else{
							$("#dg").dialog("open");
							$("#ti").html("很遗憾，冻结用户失败！");
						}
					}
				});
				$("#tu").datagrid("reload");
				setTimeout(function(){
					$("#dg").dialog("close");
				},2000);
			}
		},
		{
			text:'取消',
			iconCls:'icon-cancel',
			width:80,
			height:30,
			handler:function(){
				$("#dh").dialog("close");
			}
		}
	];
	$("#tu").datagrid({
		url:'${pageContext.request.contextPath}/user/findPage',
		fitColumns:true,
	 	striped:true,
	 	rownumbers: true,
	    singleSelect:true,
	    iconCls:'icon-edit',
		striped:true,
		pagination:true,
		pageNumber:1,
		pageSize:5,
		pageList:[5,10,15],
		fit:true,
		toolbar:tools,
		columns:[[
			{field:'img',title:'图片展示',width:60,align:'center',
				formatter:function(value,row,index){
					return "<img width='100%' height='70px' src='"+row.img+"'>";
				}
			},
			{field:'username',title:'用户名',width:50,align:'center'},
			{field:'userPassword',title:'密码',width:140,align:'center'},
			{field:'userSalt',title:'盐',width:40,align:'center'},
			{field:'userReliName',title:'法名',width:60,align:'center'},
			{field:'sex',title:'性别',width:30,align:'center'},
			{field:'sign',title:'用户签名',width:100,align:'center'},
			{field:'location',title:'用户所在地',width:100,align:'center'},
			{field:'mobilePhone',title:'手机号',width:100,align:'center'},
			{field:'userStatus',title:'用户状态',width:60,align:'center'},
			{field:'adminId',title:'上师ID',width:160,align:'center'}
		]]
	});
	$("#dg").dialog({
		width:400,
	 	height:150,
	 	iconCls:'icon-cut',
		title:'操作成功？',
	    modal:true,
		closed:true,
	});
	$("#dh").dialog({
		width:400,
	 	height:180,
	 	iconCls:'icon-cut',
		title:'操作成功？',
	    modal:true,
		closed:true,
		buttons:btns
	});
</script>
